# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/olafurj/Downloads/CLion-2018.1.5/clion-2018.1.5/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/olafurj/Downloads/CLion-2018.1.5/clion-2018.1.5/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/olafurj/Dropbox/dev/OpenWorld

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/olafurj/Dropbox/dev/OpenWorld

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/olafurj/Downloads/CLion-2018.1.5/clion-2018.1.5/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/olafurj/Downloads/CLion-2018.1.5/clion-2018.1.5/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/olafurj/Dropbox/dev/OpenWorld/CMakeFiles /home/olafurj/Dropbox/dev/OpenWorld/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/olafurj/Dropbox/dev/OpenWorld/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named OpenWorld

# Build rule for target.
OpenWorld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 OpenWorld
.PHONY : OpenWorld

# fast build rule for target.
OpenWorld/fast:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/build
.PHONY : OpenWorld/fast

OpenEngine/Cubemap.o: OpenEngine/Cubemap.cpp.o

.PHONY : OpenEngine/Cubemap.o

# target to build an object file
OpenEngine/Cubemap.cpp.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/OpenEngine/Cubemap.cpp.o
.PHONY : OpenEngine/Cubemap.cpp.o

OpenEngine/Cubemap.i: OpenEngine/Cubemap.cpp.i

.PHONY : OpenEngine/Cubemap.i

# target to preprocess a source file
OpenEngine/Cubemap.cpp.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/OpenEngine/Cubemap.cpp.i
.PHONY : OpenEngine/Cubemap.cpp.i

OpenEngine/Cubemap.s: OpenEngine/Cubemap.cpp.s

.PHONY : OpenEngine/Cubemap.s

# target to generate assembly for a file
OpenEngine/Cubemap.cpp.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/OpenEngine/Cubemap.cpp.s
.PHONY : OpenEngine/Cubemap.cpp.s

OpenEngine/Texture.o: OpenEngine/Texture.cpp.o

.PHONY : OpenEngine/Texture.o

# target to build an object file
OpenEngine/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/OpenEngine/Texture.cpp.o
.PHONY : OpenEngine/Texture.cpp.o

OpenEngine/Texture.i: OpenEngine/Texture.cpp.i

.PHONY : OpenEngine/Texture.i

# target to preprocess a source file
OpenEngine/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/OpenEngine/Texture.cpp.i
.PHONY : OpenEngine/Texture.cpp.i

OpenEngine/Texture.s: OpenEngine/Texture.cpp.s

.PHONY : OpenEngine/Texture.s

# target to generate assembly for a file
OpenEngine/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/OpenEngine/Texture.cpp.s
.PHONY : OpenEngine/Texture.cpp.s

includes/SOIL/SOIL.o: includes/SOIL/SOIL.c.o

.PHONY : includes/SOIL/SOIL.o

# target to build an object file
includes/SOIL/SOIL.c.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/SOIL/SOIL.c.o
.PHONY : includes/SOIL/SOIL.c.o

includes/SOIL/SOIL.i: includes/SOIL/SOIL.c.i

.PHONY : includes/SOIL/SOIL.i

# target to preprocess a source file
includes/SOIL/SOIL.c.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/SOIL/SOIL.c.i
.PHONY : includes/SOIL/SOIL.c.i

includes/SOIL/SOIL.s: includes/SOIL/SOIL.c.s

.PHONY : includes/SOIL/SOIL.s

# target to generate assembly for a file
includes/SOIL/SOIL.c.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/SOIL/SOIL.c.s
.PHONY : includes/SOIL/SOIL.c.s

includes/glad/include/glad/glad.o: includes/glad/include/glad/glad.c.o

.PHONY : includes/glad/include/glad/glad.o

# target to build an object file
includes/glad/include/glad/glad.c.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/glad/include/glad/glad.c.o
.PHONY : includes/glad/include/glad/glad.c.o

includes/glad/include/glad/glad.i: includes/glad/include/glad/glad.c.i

.PHONY : includes/glad/include/glad/glad.i

# target to preprocess a source file
includes/glad/include/glad/glad.c.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/glad/include/glad/glad.c.i
.PHONY : includes/glad/include/glad/glad.c.i

includes/glad/include/glad/glad.s: includes/glad/include/glad/glad.c.s

.PHONY : includes/glad/include/glad/glad.s

# target to generate assembly for a file
includes/glad/include/glad/glad.c.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/glad/include/glad/glad.c.s
.PHONY : includes/glad/include/glad/glad.c.s

includes/libconfig/libconfig/grammar.o: includes/libconfig/libconfig/grammar.c.o

.PHONY : includes/libconfig/libconfig/grammar.o

# target to build an object file
includes/libconfig/libconfig/grammar.c.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/grammar.c.o
.PHONY : includes/libconfig/libconfig/grammar.c.o

includes/libconfig/libconfig/grammar.i: includes/libconfig/libconfig/grammar.c.i

.PHONY : includes/libconfig/libconfig/grammar.i

# target to preprocess a source file
includes/libconfig/libconfig/grammar.c.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/grammar.c.i
.PHONY : includes/libconfig/libconfig/grammar.c.i

includes/libconfig/libconfig/grammar.s: includes/libconfig/libconfig/grammar.c.s

.PHONY : includes/libconfig/libconfig/grammar.s

# target to generate assembly for a file
includes/libconfig/libconfig/grammar.c.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/grammar.c.s
.PHONY : includes/libconfig/libconfig/grammar.c.s

includes/libconfig/libconfig/libconfig.o: includes/libconfig/libconfig/libconfig.c.o

.PHONY : includes/libconfig/libconfig/libconfig.o

# target to build an object file
includes/libconfig/libconfig/libconfig.c.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/libconfig.c.o
.PHONY : includes/libconfig/libconfig/libconfig.c.o

includes/libconfig/libconfig/libconfig.i: includes/libconfig/libconfig/libconfig.c.i

.PHONY : includes/libconfig/libconfig/libconfig.i

# target to preprocess a source file
includes/libconfig/libconfig/libconfig.c.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/libconfig.c.i
.PHONY : includes/libconfig/libconfig/libconfig.c.i

includes/libconfig/libconfig/libconfig.s: includes/libconfig/libconfig/libconfig.c.s

.PHONY : includes/libconfig/libconfig/libconfig.s

# target to generate assembly for a file
includes/libconfig/libconfig/libconfig.c.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/libconfig.c.s
.PHONY : includes/libconfig/libconfig/libconfig.c.s

includes/libconfig/libconfig/libconfigcpp.o: includes/libconfig/libconfig/libconfigcpp.cc.o

.PHONY : includes/libconfig/libconfig/libconfigcpp.o

# target to build an object file
includes/libconfig/libconfig/libconfigcpp.cc.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/libconfigcpp.cc.o
.PHONY : includes/libconfig/libconfig/libconfigcpp.cc.o

includes/libconfig/libconfig/libconfigcpp.i: includes/libconfig/libconfig/libconfigcpp.cc.i

.PHONY : includes/libconfig/libconfig/libconfigcpp.i

# target to preprocess a source file
includes/libconfig/libconfig/libconfigcpp.cc.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/libconfigcpp.cc.i
.PHONY : includes/libconfig/libconfig/libconfigcpp.cc.i

includes/libconfig/libconfig/libconfigcpp.s: includes/libconfig/libconfig/libconfigcpp.cc.s

.PHONY : includes/libconfig/libconfig/libconfigcpp.s

# target to generate assembly for a file
includes/libconfig/libconfig/libconfigcpp.cc.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/libconfigcpp.cc.s
.PHONY : includes/libconfig/libconfig/libconfigcpp.cc.s

includes/libconfig/libconfig/scanctx.o: includes/libconfig/libconfig/scanctx.c.o

.PHONY : includes/libconfig/libconfig/scanctx.o

# target to build an object file
includes/libconfig/libconfig/scanctx.c.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/scanctx.c.o
.PHONY : includes/libconfig/libconfig/scanctx.c.o

includes/libconfig/libconfig/scanctx.i: includes/libconfig/libconfig/scanctx.c.i

.PHONY : includes/libconfig/libconfig/scanctx.i

# target to preprocess a source file
includes/libconfig/libconfig/scanctx.c.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/scanctx.c.i
.PHONY : includes/libconfig/libconfig/scanctx.c.i

includes/libconfig/libconfig/scanctx.s: includes/libconfig/libconfig/scanctx.c.s

.PHONY : includes/libconfig/libconfig/scanctx.s

# target to generate assembly for a file
includes/libconfig/libconfig/scanctx.c.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/scanctx.c.s
.PHONY : includes/libconfig/libconfig/scanctx.c.s

includes/libconfig/libconfig/scanner.o: includes/libconfig/libconfig/scanner.c.o

.PHONY : includes/libconfig/libconfig/scanner.o

# target to build an object file
includes/libconfig/libconfig/scanner.c.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/scanner.c.o
.PHONY : includes/libconfig/libconfig/scanner.c.o

includes/libconfig/libconfig/scanner.i: includes/libconfig/libconfig/scanner.c.i

.PHONY : includes/libconfig/libconfig/scanner.i

# target to preprocess a source file
includes/libconfig/libconfig/scanner.c.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/scanner.c.i
.PHONY : includes/libconfig/libconfig/scanner.c.i

includes/libconfig/libconfig/scanner.s: includes/libconfig/libconfig/scanner.c.s

.PHONY : includes/libconfig/libconfig/scanner.s

# target to generate assembly for a file
includes/libconfig/libconfig/scanner.c.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/scanner.c.s
.PHONY : includes/libconfig/libconfig/scanner.c.s

includes/libconfig/libconfig/strbuf.o: includes/libconfig/libconfig/strbuf.c.o

.PHONY : includes/libconfig/libconfig/strbuf.o

# target to build an object file
includes/libconfig/libconfig/strbuf.c.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/strbuf.c.o
.PHONY : includes/libconfig/libconfig/strbuf.c.o

includes/libconfig/libconfig/strbuf.i: includes/libconfig/libconfig/strbuf.c.i

.PHONY : includes/libconfig/libconfig/strbuf.i

# target to preprocess a source file
includes/libconfig/libconfig/strbuf.c.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/strbuf.c.i
.PHONY : includes/libconfig/libconfig/strbuf.c.i

includes/libconfig/libconfig/strbuf.s: includes/libconfig/libconfig/strbuf.c.s

.PHONY : includes/libconfig/libconfig/strbuf.s

# target to generate assembly for a file
includes/libconfig/libconfig/strbuf.c.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/strbuf.c.s
.PHONY : includes/libconfig/libconfig/strbuf.c.s

includes/libconfig/libconfig/strvec.o: includes/libconfig/libconfig/strvec.c.o

.PHONY : includes/libconfig/libconfig/strvec.o

# target to build an object file
includes/libconfig/libconfig/strvec.c.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/strvec.c.o
.PHONY : includes/libconfig/libconfig/strvec.c.o

includes/libconfig/libconfig/strvec.i: includes/libconfig/libconfig/strvec.c.i

.PHONY : includes/libconfig/libconfig/strvec.i

# target to preprocess a source file
includes/libconfig/libconfig/strvec.c.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/strvec.c.i
.PHONY : includes/libconfig/libconfig/strvec.c.i

includes/libconfig/libconfig/strvec.s: includes/libconfig/libconfig/strvec.c.s

.PHONY : includes/libconfig/libconfig/strvec.s

# target to generate assembly for a file
includes/libconfig/libconfig/strvec.c.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/strvec.c.s
.PHONY : includes/libconfig/libconfig/strvec.c.s

includes/libconfig/libconfig/util.o: includes/libconfig/libconfig/util.c.o

.PHONY : includes/libconfig/libconfig/util.o

# target to build an object file
includes/libconfig/libconfig/util.c.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/util.c.o
.PHONY : includes/libconfig/libconfig/util.c.o

includes/libconfig/libconfig/util.i: includes/libconfig/libconfig/util.c.i

.PHONY : includes/libconfig/libconfig/util.i

# target to preprocess a source file
includes/libconfig/libconfig/util.c.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/util.c.i
.PHONY : includes/libconfig/libconfig/util.c.i

includes/libconfig/libconfig/util.s: includes/libconfig/libconfig/util.c.s

.PHONY : includes/libconfig/libconfig/util.s

# target to generate assembly for a file
includes/libconfig/libconfig/util.c.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/libconfig/libconfig/util.c.s
.PHONY : includes/libconfig/libconfig/util.c.s

includes/stb_image/stb_image.o: includes/stb_image/stb_image.cpp.o

.PHONY : includes/stb_image/stb_image.o

# target to build an object file
includes/stb_image/stb_image.cpp.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/stb_image/stb_image.cpp.o
.PHONY : includes/stb_image/stb_image.cpp.o

includes/stb_image/stb_image.i: includes/stb_image/stb_image.cpp.i

.PHONY : includes/stb_image/stb_image.i

# target to preprocess a source file
includes/stb_image/stb_image.cpp.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/stb_image/stb_image.cpp.i
.PHONY : includes/stb_image/stb_image.cpp.i

includes/stb_image/stb_image.s: includes/stb_image/stb_image.cpp.s

.PHONY : includes/stb_image/stb_image.s

# target to generate assembly for a file
includes/stb_image/stb_image.cpp.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/includes/stb_image/stb_image.cpp.s
.PHONY : includes/stb_image/stb_image.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/OpenWorld.dir/build.make CMakeFiles/OpenWorld.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... OpenWorld"
	@echo "... OpenEngine/Cubemap.o"
	@echo "... OpenEngine/Cubemap.i"
	@echo "... OpenEngine/Cubemap.s"
	@echo "... OpenEngine/Texture.o"
	@echo "... OpenEngine/Texture.i"
	@echo "... OpenEngine/Texture.s"
	@echo "... includes/SOIL/SOIL.o"
	@echo "... includes/SOIL/SOIL.i"
	@echo "... includes/SOIL/SOIL.s"
	@echo "... includes/glad/include/glad/glad.o"
	@echo "... includes/glad/include/glad/glad.i"
	@echo "... includes/glad/include/glad/glad.s"
	@echo "... includes/libconfig/libconfig/grammar.o"
	@echo "... includes/libconfig/libconfig/grammar.i"
	@echo "... includes/libconfig/libconfig/grammar.s"
	@echo "... includes/libconfig/libconfig/libconfig.o"
	@echo "... includes/libconfig/libconfig/libconfig.i"
	@echo "... includes/libconfig/libconfig/libconfig.s"
	@echo "... includes/libconfig/libconfig/libconfigcpp.o"
	@echo "... includes/libconfig/libconfig/libconfigcpp.i"
	@echo "... includes/libconfig/libconfig/libconfigcpp.s"
	@echo "... includes/libconfig/libconfig/scanctx.o"
	@echo "... includes/libconfig/libconfig/scanctx.i"
	@echo "... includes/libconfig/libconfig/scanctx.s"
	@echo "... includes/libconfig/libconfig/scanner.o"
	@echo "... includes/libconfig/libconfig/scanner.i"
	@echo "... includes/libconfig/libconfig/scanner.s"
	@echo "... includes/libconfig/libconfig/strbuf.o"
	@echo "... includes/libconfig/libconfig/strbuf.i"
	@echo "... includes/libconfig/libconfig/strbuf.s"
	@echo "... includes/libconfig/libconfig/strvec.o"
	@echo "... includes/libconfig/libconfig/strvec.i"
	@echo "... includes/libconfig/libconfig/strvec.s"
	@echo "... includes/libconfig/libconfig/util.o"
	@echo "... includes/libconfig/libconfig/util.i"
	@echo "... includes/libconfig/libconfig/util.s"
	@echo "... includes/stb_image/stb_image.o"
	@echo "... includes/stb_image/stb_image.i"
	@echo "... includes/stb_image/stb_image.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

